### ISSUE TITLE
Can there be a half-done option?

### ISSUE THREAD

**Issue by ice1000** [OrangeX4/typst-cheq#1]
Like `[-]`, similar to intellij partial commit:
![image](https://github.com/OrangeX4/typst-cheq/assets/16398479/59ad1bd0-e939-40e2-ae0b-1479b30769a6)
compared to full commit:
![image](https://github.com/OrangeX4/typst-cheq/assets/16398479/b874792e-2021-4454-9608-f80b07dd0d1b)

**Comment by OrangeX4** [comment]
Certainly, I'm planning to add more syntax, icons, and enhanced customization capabilities in the next version. Some potential syntax options can be found here: [link](https://minimal.guide/checklists#Alternate+checkboxes).

Suggestions regarding icon styles and specific API designs are also welcome.
